spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://221.148.97.239:3306/ggogitdb
    username: ggogit
    password: 111

  messages:
    basename: messages, errors
  servlet:
    multipart:
      max-file-size: 10MB
    ## 메일 발송
  mail:
    host: smtp.gmail.com #SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username:  # SMTP 서버 로그인 아이디
    password:  #SMTP 서버 비밀번호
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true #사용자 인증 시도 여부(기본값은 false)
          timeout: 5000 #socket read timeout
          starttls:
            enable: true #starttls 활성화 여부
            required: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

server:
  servlet:
    context-path: /api/v1

file: # 이미지 업로드 경로
  tmp-dir: src/main/webapp/image/tmp
  upload-dir: src/main/webapp/uploads
  upload-path: src/main/resources/static/uploads

aladin:
  api:
    key: ttbrhkddlr982013001