spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://221.148.97.239:3306/ggogitdb
    username: ggogit
    password: 111

server:
  servlet:
    context-path: /api/v1

file: # 이미지 업로드 경로
  tmp-dir: src/main/webapp/image/tmp
  upload-dir: src/main/webapp/uploads