spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 111
  h2:
    console:
      enabled: true

  messages:
    basename: messages, errors
  servlet:
    multipart:
      max-file-size: 10MB
    ## 메일 발송
  mail:
    host: smtp.gmail.com #SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username:  gksxorb147@gmail.com # SMTP 서버 로그인 아이디
    password:  tgwa wsxf yaxo zhqs #SMTP 서버 비밀번호
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true #사용자 인증 시도 여부(기본값은 false)
          timeout: 5000 #socket read timeout
          starttls:
            enable: true #starttls 활성화 여부
            required: true

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 100 #batch size 글로벌 설정
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8

jwt:
  secret: secret_ggogit_a15sf1asdf1a5s64df2a3s4df5as1df
  # 1년 : 31536000000
  access-expiration: 31536000000 # 30분
  refresh-expiration: 604800000 # 7일

server:
  servlet:
    context-path: /api/v1

aladin:
  api:
    key: ttbrhkddlr982013001

naver: # 네이버 Oauth2 로그인
  api:
    client_id: Y82lIjIMLGmIfTM3LzMr
    client_secret: aaj9FW9L6D

kakao: # 카카오 Oauth2 로그인
  api:
    client_id: 10914f073d67f4a9067f6bca8c6a75dc

file: # 이미지 업로드 경로
  tmp-dir: src/main/webapp/image/tmp
  upload-dir: src/main/webapp/uploads
  upload-path: src/main/webapp/uploads