spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 111
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update # 테스트마다 스키마 생성
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8


server:
  servlet:
    context-path: /api/v1

file: # 이미지 업로드 경로
  tmp-dir: src/main/webapp/image/tmp
  upload-dir: src/main/webapp/uploads