spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//hi.newlecture.com:1521/XEPDB1
    username: GGOGIT
    password: qmfoscl0809
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # 반환타입 패키지 여러개 적을 수 있는지?
  type-aliases-package: Recorders.ggogit.domain.**
  # 공용 핸들러 패키지 경로 추가 -----------------------------
  type-handlers-package: Recorders.ggogit.web.CommonTypeHandler
  # -----------------------------------------------------
  mapper-locations: mappers/**/*Mapper.xml
logging:
  level:
    Recorders.ggogit.domain: trace


