spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//hi.newlecture.com:1521/XEPDB1
    username: GGOGIT
    password: qmfoscl0809
    ##메시지 소스 추가
  messages:
    basename: messages, errors
server:
  servlet:
    session:
      #최초 로그인시 URL에 SID표현 x
      tracking-modes: cookie
      # 세션 타임아웃 1800초
      timeout: 1800
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: Recorders.ggogit.domain.**
  # 공용 핸들러 패키지 경로 추가 -----------------------------
  type-handlers-package: Recorders.ggogit.web.CommonTypeHandler
  # -----------------------------------------------------
  mapper-locations: mappers/**/*Mapper.xml
logging:
  level:
    Recorders.ggogit.domain: trace
    org.springframework.jdbc: trace


