# ================================================== #
# 내부 변수
@leafId = 47
@seedBookId = 1
@seddEtcId = 1
@tagId = 10001
# ================================================== #

# ================================================== #
# 도서 리프

### 첫번쨰 도서 리프 생성
POST {{host}}/api/v1/book/first/leaves

### 도서 리프 생성
POST {{host}}/api/v1/book/leaves

### 도서 리프 수정
PUT {{host}}/api/v1/book/leaves/{{leafId}}

### 도서 리프 삭제
DELETE {{host}}/api/v1/leaves/{{leafId}}

# ================================================== #
# 도서 리프
### 첫번째 기타 리프 생성
POST {{host}}/api/v1/etc/first/leaves

### 기타 리프 생성
POST {{host}}/api/v1/etc/leaves

### 기타 리프 수정
PUT {{host}}/api/v1/etc/leaves/{{leafId}}

### 기타 리프 삭제
DELETE {{host}}/api/v1/etc/leaves/{{leafId}}

# ================================================== #

# ================================================== #
# 리프 조회
### 리프 조회

GET {{host}}/api/v1/leaves/{{leafId}}/all

# ================================================== #

# ================================================== #
# 리프 태그

### 리프 태그 생성
POST {{host}}/api/v1/leaf/tags
Content-Type: application/json

{
  "name": "태그 생성1"
}

### 리프 태그 조회
GET {{host}}/api/v1/leaf/tags

### 리프 태그 디테일 조회
GET {{host}}/api/v1/leaf/tags/{{tagId}}


### 리프 태그 생성
#> {%
#    client.test("Response status is 200", function() {
#        client.assert(response.status === 200, "Response status is not 200");
#    });
#
#    client.test("Response contains Hello, World!", function() {
#        client.assert(response.body === "Hello, World!", "Response does not contain expected message");
#    });
#%}

