# @env=dev
# ================================================== #
# 내부 변수
@treeId = 1
@seedBookId = 1
@seddEtcId = 1
# ================================================== #

# ================================================== #
# 도서 리프
### 선택 도서 트리 생성
POST https://ggogit.taecobug.io:8080/api/v1/trees/auto
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "bookId": 1,
  "treeTitle": "Python을 공부하기 위한 트리",
  "description": "Python을 공부하기 위한 트리입니다.",
  "visibility": true
}