# @env=dev
# ================================================== #
# 내부 변수
@treeId = 10000
@seedBookId = 1
@seddEtcId = 1
# ================================================== #

# ================================================== #
# 도서 리프

### 트리 리프 조회
GET {{host}}/trees/{{treeId}}/leafs
