CREATE OR REPLACE VIEW VW_BOOK_CATEGORY_LIST
AS
SELECT B.IMAGE_FILE, B.TITLE, B.PUBLIC_DATE, B.AUTHOR, B.PUBLISHER, B.CREATE_TIME, BC.NAME CATEGORY
FROM BOOK B LEFT JOIN BOOK_CATEGORY BC ON B.BOOK_CATEGORY_ID = BC.ID;

COMMENT ON TABLE VW_MEMOIR_CL_CNT IS '도서 검색 결과 미리보기 결과 반환';