CREATE OR REPLACE VIEW VW_MEMOIR_CL_CNT
AS
SELECT M.ID, M.TREE_ID, M.TITLE, COUNT(C.ID) COMMENT_CNT, COUNT(L.ACTIVE) LIKE_CNT
FROM (SELECT * FROM MEMOIR WHERE MEMOIR.IS_DELETED = 0) M
         LEFT JOIN MEMOIR_COMMENT C ON M.ID = C.MEMOIR_ID
         LEFT JOIN (SELECT * FROM MEMOIR_LIKE l WHERE l.ACTIVE = 1) L ON M.ID = L.MEMOIR_ID
GROUP BY M.ID, M.TREE_ID, M.TITLE, C.ID, L.ACTIVE;

COMMENT ON TABLE VW_MEMOIR_CL_CNT IS '회고록 댓글 수, 좋아요 수'