spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://221.148.97.239:3306/ggogitdb
    username: ggogit
    password: 111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

file: # 이미지 업로드 경로
  tmp-dir: src/main/webapp/image/tmp
  upload-dir: src/main/webapp/uploads