-- 맴버 생성
INSERT INTO MEMBER (ID, EMAIL, PASSWORD, NICKNAME, INTRODUCTION, UPDATE_TIME, CREATE_TIME)
VALUES (999, 'test@gmail.com', '1234', '테스트', '테스트입니다.', SYSDATE, SYSDATE);

-- 씨드 생성
INSERT INTO SEED (ID, NAME)
VALUES (999, '씨드 테스트');

-- 트리 생성
INSERT INTO TREE (ID, MEMBER_ID, SEED_ID, TITLE, DESCRIPTION, BOOK_MARK_COUNT, VISIBILITY, UPDATE_TIME, CREATE_TIME)
VALUES (999, 999, 999, '테스트', '테스트입니다.', 0, 'PUBLIC', SYSDATE, SYSDATE);